version: '3'

services:
  python:
    image: python-3.9.5
    volumes:
      - code-src:/code-src
      
volumes:
  code-src:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
